# Generated by Django 3.2.2 on 2022-07-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'Javascript'), ('C++', 'C Plus Plus')], default='PY', max_length=10),
        ),
    ]
