# Generated by Django 3.2.2 on 2022-07-21 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0002_category_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
