# Generated by Django 3.2.2 on 2022-07-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0003_auto_20220721_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
