# Generated by Django 3.2.2 on 2022-08-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0006_usercompletedchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompletedchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='Challenges.challenge'),
        ),
    ]
