# Generated by Django 3.2.2 on 2022-08-03 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Challenges', '0007_alter_usercompletedchallenge_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompletedchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercc', to='Challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='usercompletedchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercc', to=settings.AUTH_USER_MODEL),
        ),
    ]
