# Generated by Django 3.2.2 on 2022-08-04 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Challenges', '0010_auto_20220803_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompletedchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='usercompletedchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
