# Generated by Django 3.2.2 on 2022-08-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0012_usercomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
