# Generated by Django 3.2.2 on 2022-08-24 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Challenges', '0013_delete_usercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeUserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=500)),
                ('Challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenges.challenge')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
